[DSS-1]
manufacturer = "Korg"
id = "dss-1"

[[DSS-1.commands]]
name = "Program Parameter Request"
sysex = "F0 42 3n 0B 10 pp F7"
parameters.n = "Channel"
parameters.p = "Parameter"
alias = ["pr"]

[[DSS-1.commands]]
name = "Mode Request"
sysex = "F0 42 3n 0B 12 F7"
parameters.n = "Channel"
alias = ["mr"]

[[DSS-1.commands]]
name = "PCM Data Request"
sysex = "F0 42 3n 0B 14 aaaaaaaaaaaa bbbbbbbbbbbb F7"
parameters.n = "Channel"
parameters.a = "Start Address"
parameters.b = "Last Address"
alias = ["pcm"]

[[DSS-1.commands]]
name = "Parameter Change"
sysex = "F0 42 3n 0B 41 pp vv F7"
parameters.n = "Channel"
parameters.p = "Program"
parameters.v = "Value"
alias = ["pc", "param", "parameter", "parameter-change"]

[[DSS-1.commands]]
name = "Mode Change"
sysex = "F0 42 3n 0B 42 mm F7"
parameters.n = "Channel"
parameters.p = "Mode"
parameters.v = "Value"
alias = ["mc", "mode", "mode-change"]

